FROM public.ecr.aws/lambda/nodejs:20

# Set working directory
WORKDIR /var/task

# Copy your project files
COPY package*.json ./
COPY . .

# Install dependencies (omit optional, e.g. Puppeteer binary)
RUN npm install --omit=optional

# Set Puppeteer environment
ENV PUPPETEER_EXECUTABLE_PATH=/opt/chromium
ENV AWS_EXECUTION_ENV=true

# Command for Lambda function entry point
CMD ["index.fetch"]
